<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="cardValidationSystemService"
     targetNamespace="http://xmlns.oracle.com/orderProcessingSystem/cardValidationSystem/cardValidationSystemService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/orderProcessingSystem/cardValidationSystem/cardValidationSystemService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="cardValidationSOAPService">
        <plnk:role name="cardValidationPort" portType="tns:cardValidationPort"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/orderProcessingSystem/cardValidationSystem/cardValidationSystemService"
         location="cardValidationSystemService.wsdl"/>
</wsdl:definitions>
